import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from 'next/font/local' // dung font tai ve local lu o app / font / ...
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "./AppProvider";
import { cookies } from "next/headers";

// const inter = Inter({ subsets: ["latin"] }); // font mac dinh

const roboto = Roboto({ // font moi Roboto
  subsets: ["vietnamese"], weight: [
    '100',
    "300",
    '400',
    '500',
    '700',
    '900',
  ]
});

const myFont = localFont({
  src: [{
    path: './fonts/Roboto/Roboto-Thin.ttf',
    weight: '100',
  },
  {
    path: './fonts/Roboto/Roboto-Regular.ttf',
    weight: '400',
  },
  ],
  display: 'swap',
  // variable: '--font-roboto'
}) // font da tai ve local 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies()
  const sessionToken = cookieStore.get('sessionToken')

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={inter.className}
        className={roboto.className}
      // className={`${myFont.variable}`}
      // className={myFont.className}
      >
        <Toaster />
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <AppProvider inititalsessionToken={sessionToken?.value}>{children}</AppProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
